# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

udp_path_logger <- function(port, path) {
    invisible(.Call(`_udpbroadcastreceiver_udp_path_logger`, port, path))
}

udp_callback_logger <- function(port, callback) {
    invisible(.Call(`_udpbroadcastreceiver_udp_callback_logger`, port, callback))
}

